# Generated by Django 3.2.5 on 2021-08-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
