# Generated by Django 3.2.6 on 2021-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=50000000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
