# Generated by Django 3.2.6 on 2021-08-13 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('tag', models.CharField(max_length=32, verbose_name='태그')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('img_file_name', models.CharField(max_length=64, verbose_name='이미지파일')),
                ('accumulated_amount', models.PositiveIntegerField(default=0, verbose_name='펀딩금액')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '아이디어 펀딩',
                'verbose_name_plural': '아이디어 펀딩',
                'db_table': 'writing',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='FundingLog',
            fields=[
                ('funding_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('funding_amount', models.IntegerField(null=True)),
                ('funding_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('writing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.writing')),
            ],
            options={
                'db_table': 'funding_log',
            },
        ),
    ]
