# Generated by Django 3.2.5 on 2021-07-28 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='글제목')),
                ('contents', models.TextField(verbose_name='글내용')),
                ('tag', models.CharField(max_length=32, verbose_name='게시판종류')),
                ('write_dttm', models.DateTimeField(auto_now=True, verbose_name='마지막수정일')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('capital', models.PositiveIntegerField(default=0, verbose_name='펀딩금액')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='포인트')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='잔액')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
