# Generated by Django 3.2.5 on 2021-08-11 17:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='글제목')),
                ('contents', models.TextField(max_length=255, verbose_name='글내용')),
                ('tag', models.CharField(max_length=32, verbose_name='게시판종류')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='data published')),
                ('capital', models.PositiveIntegerField(default=0, verbose_name='펀딩금액')),
                ('userid', models.ForeignKey(db_column='writerid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'Writing',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.PositiveIntegerField(default=0, verbose_name='투자금액')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='data published')),
                ('user_id', models.ForeignKey(db_column='funding_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원ID')),
                ('writing_id', models.ForeignKey(db_column='writing_id', on_delete=django.db.models.deletion.CASCADE, to='pybo.writing', verbose_name='글ID')),
            ],
            options={
                'db_table': 'funding',
            },
        ),
    ]
