# Generated by Django 3.2.6 on 2021-08-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinglog',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='fundinglog',
            name='writing_id',
            field=models.ForeignKey(db_column='writing_id', on_delete=django.db.models.deletion.CASCADE, to='pybo.writing'),
        ),
    ]
