# Generated by Django 3.2.5 on 2021-07-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='writing',
            table='writing',
        ),
    ]
