# Generated by Django 3.2.5 on 2021-08-04 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20210804_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={'ordering': ['point']},
        ),
        migrations.AlterModelOptions(
            name='writing',
            options={'ordering': ['pub_date']},
        ),
        migrations.RemoveField(
            model_name='writing',
            name='write_dttm',
        ),
        migrations.AddField(
            model_name='writing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='data published'),
        ),
    ]
